### ISSUE TITLE
Another unhandled event : APPLICATION_COMMAND_PERMISSIONS_UPDATE

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#1003]
**To Reproduce:** /
**Expected Behavior:** Event should be handled
**Actual Behavior:** This event isn't handled so we 
**Version:** 3.1.7
**Other:** https://github.com/discord/discord-api-docs/pull/2737

**Comment by NovaFox161** [comment]
I can comment here now because this is officially public information.

Discord is massively changing the existing application command permission system and it is expected that this event will also change from what the current payload contains. 

As such, I personally believe it would be wasted effort to build this into the library only for us to need to scrap it all in a month or two when the previewed changes reach mainline.
