### ISSUE TITLE
Support sending attachments on ephemeral messages

### ISSUE THREAD

**Issue by WeeskyBDW** [Discord4J/Discord4J#1006]
**Feature Description:** 
Add a way to send text and/or attachments on ephemeral  messages

**Justification:** 
Discord recently add the possibility to send attachments in ephemeral messages.

**Comment by quanticc** [comment]
Do you mean this object is changing, or something else? https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-data-structure

Otherwise for edits and follow-ups, Multipart request support is already implemented on latest snapshots (3.1.8-SNAPSHOT and 3.2.0-SNAPSHOT)

**Comment by WeeskyBDW** [comment]
Quote from Discord devs

> Ephemeral Attachments

> OwO! You can now attach files to ephemeral messages. There's also a new ephemeral boolean property on attachment objects (see the docs for more info).
