### ISSUE TITLE
connection timed out: discord.com/66.220.146.94:443

### ISSUE THREAD

**Issue by ToShared** [Discord4J/Discord4J#1076]
connection timed out: discord.com/66.220.146.94:443

code is easy

`     final DiscordClient client = DiscordClient.create("***");

        Mono<Void> login = client.withGateway((GatewayDiscordClient gateway1) -> Mono.empty());

        login.block();`

**Comment by NovaFox161** [comment]
This is not an issue with the library. This could be caused by any of the following:
- Your firewall is blocking the connection
- Your internet dropped out/have no internet connection
- Your antivirus is blocking the connection
- Your router is blocking the connection
- And likely many many other possible causes.

At the end of the day, this is a networking issue somewhere between the application and discord, not the library. 

IF you require future help with the library, please join [our Discord server](https://discord.gg/d4j).
