### ISSUE TITLE
Hi, I wonder about compiled size

### ISSUE THREAD

**Issue by broken1arrow** [Discord4J/Discord4J#1110]
**Feature Description:** Some suggestion for reduce the size .

**Justification:** You had no help section or anything, But right now I have added around 17Mb of dependences to even get it starting
was a lot of  dependences I needed to shade. 

You talked about this is modular design but seams to demand 5 different dependency's to run even the simple code here https://docs.discord4j.com/quickstart. Is it something I have done wrong here?

**Comment by NovaFox161** [comment]
Compiled size really doesn't matter unless you are working on an embedded system, and even then, you probably shouldn't be using a bunch of java libraries in those circumstances. 

Like, there's really no valid use cases anymore for reducing compile size when its only a few megabytes. Hell, if you use Spring Boot packaged jar size can go all the way up to 200mb and that's perfectly normal. 17mb especially is basically nothing for a sever-side application. If this were webdev, I'd certainly agree about a need for reducing the sizes of binaries, but its not, its Java.

**Comment by broken1arrow** [comment]
> Compiled size really doesn't matter unless you are working on an embedded system, and even then, you probably shouldn't be using a bunch of java libraries in those circumstances.
> 
> Like, there's really no valid use cases anymore for reducing compile size when its only a few megabytes. Hell, if you use Spring Boot packaged jar size can go all the way up to 200mb and that's perfectly normal. 17mb especially is basically nothing for a sever-side application. If this were webdev, I'd certainly agree about a need for reducing the sizes of binaries, but its not, its Java.

Trust me, in this case they will ask me why on the *** is the jar file 1/20Mb (is a plugin and many users will complain on the size and also limit so we can't upload on some sites).

**Comment by NovaFox161** [comment]
A minecraft plugin? Yeah, it really does not matter in that case. The Minecraft world itself will balloon to several gigabytes, A 17mb plugin is nothing in comparison. And the server jar itself typically runs to 100mb+. If users complain, then that's because they are misinformed and ignorant of how Java actually works. Again, its a server-side application, jar size really doesn't matter that much when storage is as cheap as it is. There's no value in reducing the compiled size of a jar file unless it meets certain use-cases like being on an embedded system (eg, a satellite)

**Comment by broken1arrow** [comment]
> A minecraft plugin? Yeah, it really does not matter in that case. The Minecraft world itself will balloon to several gigabytes, A 17mb plugin is nothing in comparison. And the server jar itself typically runs to 100mb+. If users complain, then that's because they are misinformed and ignorant of how Java actually works. Again, its a server-side application, jar size really doesn't matter that much when storage is as cheap as it is. There's no value in reducing the compiled size of a jar file unless it meets certain use-cases like being on an embedded system (eg, a satellite)

Some servers not offer more and 1/3Gb so (yeah they want it cheep host).

The problem with over 5mb is they can't directly downloaded on the site (is problem for some users because of the server host they use). 

The Other thing is what you mentioned they don't know how it works. I see even they some say big size will use more resources 🤔🤦

**Comment by NovaFox161** [comment]
> Some servers not offer more and 1/3Gb so (yeah they want it cheep host).
Then that's a problem on their end, and storage even on cheap hosts in cheap and can usually be upgraded without upgrading the more expensive parts of hosting (network, CPU, RAM, etc). Plus, like I mentioned the world will balloon in size anyway so that really is at most a hobby server and a 17mb plugin is still nothing. In fact, assuming that they are measuring a GB as 1000MB, then a 17mb plugin is only `0.57%` of their total 3GB of storage.

> The problem with over 5mb is they can't directly downloaded on the site (is problem for some users because of the server host they use).
Not sure what sites you are talking about, but I have experience myself with some of the popular plugin sites and none of them have such an artificially low limit. Beyond that, you can just host the jar file on GitHub and provide the link to it as these sites also allow "external download sites"

> The Other thing is what you mentioned they don't know how it works. I see even they some say big size will use more resources 🤔🤦
This is completely false and irrelevant when talking about such a small file size. If this were a 10gb file, then we could discuss this, but at 17mb, this really will not have any measurable impact on performance. If such a system would have a performance impact with this sort of file size, then that system would not even be capable of running a Minecraft server anyway.

> I start this if I could cute down some dependency's I likely not use.
There are really no dependencies within D4J that we include that are not required. You can only cut down on dependency sizes so much, and again, this is only 17mb. Spring Boot is notorious for bloating jar files and regularly pushes past 100-200mb in the final shaded jar. You are more than welcome to try, but I've already explained that there is no value in trying this as 17mb is extremely tiny in the grand scheme of things, and if you really value that that much, then you probably should not be using libraries at all, period.

**Comment by Azn9** [comment]
For a Minecraft plugin, you can "cheat" by using the "libraries" section of the plugin.yml file (see https://www.spigotmc.org/wiki/plugin-yml/) to make the server download the libraries instead of shadowing them in the plugin jar. Keep in mind though that this might not work at 100% and is only working for libraries available on maven central. Plus you need a recent server (1.16.5+ IIRC).

**Comment by broken1arrow** [comment]
> For a Minecraft plugin, you can "cheat" by using the "libraries" section of the plugin.yml file (see https://www.spigotmc.org/wiki/plugin-yml/) to make the server download the libraries instead of shadowing them in the plugin jar. Keep in mind though that this might not work at 100% and is only working for libraries available on maven central. Plus you need a recent server (1.16.5+ IIRC).

I try that but it complain on missing classes. Specially the netty was really a pain

**Comment by broken1arrow** [comment]
Ether way I made it almost work at least. It give me this when type in discord chat when write some test commands. I removed some of the data (when use getMessage). 

```
[13:06:03 INFO]: event eventMessage Message{data=MessageData{id=number, channelId=number, guildId=Possible{number}, author=UserData{id=number, username=name, discriminator=number, avatar=number, banner=Possible.absent, accentColor=Possible.absent, bot=Possible.absent, system=Possible.absent, mfaEnabled=Possible.absent, locale=Possible.absent, verified=Possible.absent, email=Possible.absent, flags=Possible.absent, premiumType=Possible.absent, publicFlags=Possible{0}}, member=Possible{PartialMemberData{nick=Possible{Optional.empty}, roles=number, joinedAt=number, premiumSince=Possible{Optional.empty}, deaf=false, mute=false, communicationDisabledUntil=Possible{Optional.empty}}}, content=, timestamp=2022-12-31T12:06:02.980000+00:00, tts=false, mentionEveryone=false, mentions=[], mentionRoles=[], mentionChannels=null, attachments=[], embeds=[], reactions=null, nonce=Possible{number}, pinned=false, webhookId=Possible.absent, type=0, activity=Possible.absent, application=Possible.absent, applicationId=Possible.absent, messageReference=Possible.absent, flags=Possible{0}, stickers=null, stickerItems=null, referencedMessage=Possible{Optional.empty}, interaction=Possible.absent, components=[]}}
```

**Comment by broken1arrow** [comment]
Seams discord has done changes in the api over time. I try make something like this work but seams that only work with message events and with that option you can't see the user input (even if you set Message Content Intent i dev tools). 

I want to send a image to discord and only find you can send strings,numbers an soo on. if you use command event. 

```
	InputStream sort = Dani.getInstance().getLeaderBoard().renderImage(Dani.getInstance().getPlayerCache().sortmoney());

		messageUpdateEvent.getMessage().getChannel().block().createMessage(messageCreateSpec ->
				messageCreateSpec.addFile("output.png", sort)
		).block();

```

**Comment by NovaFox161** [comment]
That's not an error, if there was an error in the console, you didn't paste it and only posted the json definition.

**Comment by broken1arrow** [comment]
> That's not an error, if there was an error in the console, you didn't paste it and only posted the json definition.

was not an error was my debug message. seams you can't getcontent any more from client on a server (I try several ways). no errors but always empty string (only if bot post it return something). It works when type to the bot directly. 

So try work without that option.

**Comment by Azn9** [comment]
> > That's not an error, if there was an error in the console, you didn't paste it and only posted the json definition.
> 
> was not an error was my debug message. seams you can't getcontent any more from client on a server (I try several ways). no errors but always empty string (only if bot post it return something). It works when type to the bot directly.
> 
> So try work without that option.

Have-you enabled the message content intent both in the dev panel and in your bot startup ?

**Comment by broken1arrow** [comment]
> 

yes should be set. 

`	this.client = DiscordClient.create(token)
				.gateway()
				.setEnabledIntents(IntentSet.of(
						Intent.DIRECT_MESSAGE_REACTIONS, Intent.DIRECT_MESSAGE_TYPING, Intent.DIRECT_MESSAGES,
						Intent.GUILD_MESSAGE_REACTIONS, Intent.GUILD_MESSAGES, Intent.GUILD_MESSAGE_REACTIONS
				))
				.login()
				.block();`

**Comment by NovaFox161** [comment]
you need to enable the message content intent in the discord developer portal for the bot.

**Comment by broken1arrow** [comment]
> you need to enable the message content intent in the discord developer portal for the bot.
Yeah that are fixed and it has admin perms the bot.
![perms](https://user-images.githubusercontent.com/16368286/210154953-6d36db71-f37d-40a3-9888-0cb5bb27625b.PNG)
