### ISSUE TITLE
java.lang.ClassNotFoundException: com.aayushatharva.brotli4j.Brotli4jLoader on bot login

### ISSUE THREAD

**Issue by justlofe** [Discord4J/Discord4J#1279]
**To Reproduce:** 
I wrapped Discord4J in a bukkit plugin, tested it on a local server, and everything is okay.
When i installed it on real server, it won't start. Maybe there a problem in JDK.

**Expected Behavior:** just a normal start ^_^

**Actual Behavior:** There is a big stacktrace: https://hastebin.com/share/epiguciqip.php

**Version:** 3.2.6

**Other:** 
JDK on my PC (local server): java 22.0.1 2024-04-16 (OpenJDK)
JDK on a server: 21.0.3 (Temurin-21.0.3+9 from Eclipse Adoptium). The JVM is a OpenJDK 64-Bit Server VM.

**Comment by Azn9** [comment]
Hello, one of the base error is `Caused by: java.lang.ClassNotFoundException: com.aayushatharva.brotli4j.Brotli4jLoader`
Make sure this class is packaged in your plugin or that you installed any required library.
This is not an issue with D4J itself too, but rather netty. Minecraft is known to have issues with outdated netty versions, you may want to relocate it (https://docs.discord4j.com/frequently-asked-questions#im-getting-javalangnosuchmethoderror-ionetty-or-javalangnoclassdeffounderror-comfasterxml). However, if everything works on local, maybe there's a firewall or something that block the connection 🤔

**Comment by justlofe** [comment]
Simply, but relocating libraries fixed problem. Thank you!
