### ISSUE TITLE
Bot's stuff resets on reconect

### ISSUE THREAD

**Issue by weeryan17** [Discord4J/Discord4J#258]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
So after my bot is up for a long time it the playing status get's set to nothing and the bot disconnects from connected voice channels. after talking about this in the bug-reports channel we detained this happens most lickly because of reconnects.

### Steps to Reproduce
1. Make bot and set a playing message and connect it to a voice channel
2. Wait for reconnect.

...

**Expected behavior:** Bot reconnects and re joins the channel and keeps playing message

**Actual behavior:** Bot reconects and playing message is reset and get's dissconected for all voice channels

**Version affected:** dev-SNAPSHOT latest versrion

### Additional Information
We talked about this in the bug reports channel.

**Comment by GrandPanda** [comment]
Voice reconnects will come in the future (being put on hold until after the release of 2.8)

The status being reset is semi-intentional because of how status for the self user has been dealt with in the past. We have previously treated this as "untrackable" state because of the nature of Discord allowing multiple separate programs to open connections to the gateway on the same token at the same time. Because status updates are not received for yourself, it is possible for one program to update the status of the user without the other ever knowing (Therefor throwing the other's status state out of sync). However, this is seen as an edge case by many. The solution for this is being discussed internally. 

Feel free to comment with your thoughts on this issue.

**Comment by JamesGallicchio** [comment]
How does the Discord app track user statuses with multiple clients? I'm guessing it requests status information every minute to keep it updated?

**Comment by weeryan17** [comment]
Is their a way I can check for reconnects and manually set everything again my self?

**Comment by JamesGallicchio** [comment]
@weeryan17 DisconnectedEvent and ReconnectSuccessEvent are thrown on disconnect/reconnect, and then you can set the status again. That is a viable workaround for now, but doesn't resolve the underlying issue.

**Comment by weeryan17** [comment]
Did you guys fix this in dev because it seams to not happen any more?
