### ISSUE TITLE
Delegation of Individual Properties of Specs

### ISSUE THREAD

**Issue by danthonywalker** [Discord4J/Discord4J#440]
Specs are a wonderful solution to modifying multiple properties of a Discord entity in one request. This is a vast improvement over v2 where changing multiple properties of any entity required multiple requests to be sent to Discord. However, with their use comes some questionable ease of use.

## The Problem
Let's look at `MessageCreateSpec` for any `MessageChannel`. To send a simple non-embed message, either of the following is required:
`messageChannel.createMessage(spec -> spec.setContent("Hello World"))`
or
`messageChannel.createMessage(new MessageCreateSpec().setContent("Hello World"))`
The first is a `Consumer` variant specifically to encapsulate the spec which makes it nicer to use in code blocks and reactive chains while the second is "raw" so external creation may be applied if necessary (such as needing to build from a database).

However, this is admittedly not as "easy" as `messageChannel.createMessage("Hello World")`, which was added in 691b3b and simply delegates to one of the spec variants.

This brings up a consistency issue. What about all the other specs? Shouldn't they deserve the same treatment?

### Nothing
We simply ignore this consistency problem, and only `MessageChannel#createMessage(String)` is the exception.

### Apply Retroactively on Demand
We add these delegations when demand for their use is highly requested. Sending a simple message is frequent enough to warrant it, but who are we decide what exactly is "highly requested"? Furthermore, this only just worsens the consistency. Some properties have singular properties while others don't? Not only is it a consistency issue, but may also prove to be confusing for the end-user programmer. They'll see these singular properties and, while attempting to find one that we haven't delegated yet, may be confused on where to look to apply it.

### Delegate Everything
We make single property delegations for every property for every spec where it is valid. This will require a lot of tedious work, but removes the consistency problem and makes our API "easier" to use for cases where single property application is only needed.

**Comment by quanticc** [comment]
Having "common usage" methods to shortcut the spec is fine with me. In the future more may pop up depending on request.

Specs are a low level way to build a request and, in my opinion, should not be the sole option moving forward.

**Comment by austinv11** [comment]
I agree with @quanticc. Specs can be cumbersome if all the user desires is a simple, single field change--especially for frequently used variants (see: sendMessage(String)). So I think it's fine to start with a bit of arbitrariness in what we choose to overload for now, based on user input. 

I should also say I am not totally opposed to having single field variants for every single spec, honestly. The goal of core with Reactor should be to make code *elegant* and needing to mess with specs for every single call doesn't lead to elegant method chains in all cases. This is not just because I like looking at code, mind you, but it may help users read and maintain their own code as it's very easy for reactor chains to become 🍝

**Comment by danthonywalker** [comment]
The elegance is a non-issue, this is why there are two varying options for specs. The raw type and Consumer type. in a chain the Consumer type keeps the code "contained" within the lambda, and for single property variants, this is just a one-liner arrow call; or you can pass a raw type into it with some type of map + method reference.
So I side with @GrandPanda more so, though I'd take it to the extreme and don't even allow MessageChannel#sendMessage(String), but I'll just let that slide I suppose.

**Comment by austinv11** [comment]
I see the consumer type differently, as it lazily evaluates and allows users to reuse non-state sharing code more easily. So it's more function than form for me.

 What makes specs clunky for me (this is not necessarily a flaw) is that if I wanted to create a message which only sent a string, for example, I'd have to use this: `new MessageCreateSpec().setContent(<string>)` in this case, the `new` keyword looks kinda gross (subjective) and it is much more verbose than simply passing `<string>` (objective). Specs were designed with the intention of making multi-param requests much nicer, but this is to the detriment of single-param requests.

**Comment by JamesGallicchio** [comment]
I find `messageChannel.createMessage(spec -> spec.setContent("Hello World"))` quite clean, honestly.

Perhaps make clearly distinct names for the "shortcut" overloads. Make a `createTextMessage(string)` or something. That way the specifically requested, very specific overloads can be distinguished from the general spec methods.

For anything that modifies multiple parameters at once, the spec overload is very clean. For most single parameters, it's also acceptably readable and clean. Only the most commonly used methods like `createTextMessage(string)` deserve to exist as separate methods. Having another method for each single param would be very unnecessary and honestly would make the methods harder to use ("Ugh I have to read through these 15 method signatures to find the right one" instead of one method that lets you use the spec).

Another possibility to consider if you find the spec methods too tedious would be to make the spec a bit more streamlined- think something like
`createMessage(s -> s.content(string).attachments(att))` but that's much more subjective and honestly isn't a big difference.

**Comment by danthonywalker** [comment]
@austinv11 For the createMessage(String), that *should* be `createMessage(spec -> spec.setContent("conents"))`, not the `new` keyword.

**Comment by austinv11** [comment]
@JamesGallicchio 
I think that distinct shortcut names should be contextual. I find the `createTextMessage` method to be kinda awkward, for example. However, for something like changing nicknames `changeNickname` is acceptable.

Also, you are right about the single parameter pollution, but we need a distinct policy to determine what deserves a shortcut. I'd like to remove arbitrary reasoning from the decision making process. Simply adding shortcuts for all possible single param variants is a very easy way to eliminate that and it also ensures that all possible users are happy. And I don't think trudging through methods is very difficult, when you have a keyword in mind. I think that if I wanted to edit a nickname, figuring out that I need the editGuildMember method instead of a method containing "nickname" would be more difficult. Plus we are using reactor, which requires users to trudge through waaaaaay more methods on a regular basis. 

@danthonywalker 
"Should", this doesn't mean all users will use it--preventing their complaints. And also if that is the case, why does the non-consumer overload exist?

**Comment by danthonywalker** [comment]
We discussed a while back during internal discussions on how to handle these types of things, and I originally came up with the `Consumer` variant specifically for the purposes of single properties.
Relevant link to the discussion: https://discordapp.com/channels/208023865127862272/210938552563925002/399370401576124416
![capture1](https://user-images.githubusercontent.com/6114565/44631854-078c6a80-a92f-11e8-8fa4-d951d2d0f778.PNG)

Screenshot for those not in the cool chat ;)

**Comment by austinv11** [comment]
That discussion doesn't mention that its for single parameters 🤔. And I think that the non-consumer overload is objectively worse, so I don't get its purpose anymore

**Comment by danthonywalker** [comment]
As the Javadoc says, to allow external building in case your properties are coming from blocking sources (which we should expect, most people use SQL which means JDBC which means blocking which is a no to do in reactor contextes)
And even if not, how are you supposed to get those parameters into a Spec with the Consumer variant?

**Comment by austinv11** [comment]
For blocking sources, I don't get how it's difficult to pass variables to the inside of a lambda from the blocking source. Can you not either get them within the body of the consumer or retrieve them and assign them to effectively final variables before you declare your lambda or am I misunderstanding?

**Comment by danthonywalker** [comment]
I suppose. Assume we do remove non-Consumer variants, that doesn't answer really the topic of this issue.

**Comment by JamesGallicchio** [comment]
Austin brings up a good point about naming conventions and how it wouldn't be intuitive to look to some editGuildMember method to change the nickname of a user. So what if we make the spec methods more consistent (and concise) in naming? On entities that are editable, just have two `edit` spec methods (consumer and spec) so that nickname changes would simply be `member.edit(s -> s.nickname(newNick))`. And that would be consistent across editable entities. Once a user knows to use the edit methods, it becomes pretty intuitive.

I think the createX(spec stuff) methods are already all like that, so again, it becomes intuitive once one knows what to look for.


As for the "convenience" methods- can we figure out how many of these convenience methods users would actually use? Like, ask people to share what edit/create methods they use the most in their codebase? (Or just look at our own codebases to see?)

Personally, I only use createMessage(string) regularly. I wouldn't use any other single param variants more than one or two times in a bot.

**Comment by danthonywalker** [comment]
All specs that create something are `createX` based off the thing they are created off of (for example, you create a message off of a MessageChannel, so MessageChannel#createMessage)
All specs that edit something are simply `edit` on the thing they are edited off of (for example, Member#edit).
This is as concise as I can possible conceive it.

**Comment by JamesGallicchio** [comment]
Oh, can't find an editGuildMember method @austinv11 was referring to.

I also have another question- how many utility methods should there be that do the same thing but on different entities? It seems to be a parallel to this conversation. If we have a Member#changeNickname(string) method, should we also have a Guild#changeMemberNickname(snowflake, string) method?

Would the latter be implemented by delegating to the former? I think the latter can make the request without having to request/get from the cache the Member object, so the two could do subtlely different things, but I dunno if it would just be implemented by getting the member object anyways..?

**Comment by danthonywalker** [comment]
Well that's what we are discussing and is the nature of this PR. I am in favor of no more utilities and in fact strip away changeNicknames. I'd do createMessage(String) too, but I know I know that's very unpopular so I'll let that be for now.

**Comment by austinv11** [comment]
I don't think stripping away utilities is productive, because what is the harm, exactly?

**Comment by danthonywalker** [comment]
Lack of any sort of consistency. And if we apply the single property edits to everything, that is just a lot more code to maintain and maintain being consistent i.e., we need to be consciously aware of new properties being added to apply this standard as well.

**Comment by danthonywalker** [comment]
Plus, it may discourage bad design. Users may instead of doing single-property changes across multiple requests instead of using the purpose of the Spec which is to consolidate that all to one request. This goes back to @GrandPanda comment.

**Comment by austinv11** [comment]
I mean, if we add new properties many other things need to be updated to reflect that and I don't think adding a single additional method to that changelist is a significantly higher burden. And the consistency point is why I'm in favor of methods for all properties. 

And I think the only potential for bad design is on PATCH requests. And even so, I think sufficient documentation on behavior is more than enough. Since we expect users to learn Reactor for v3, I think we can expect more from users in terms of their usage of docs.

**Comment by danthonywalker** [comment]
It's just one more thing to be conscious about. It's easy enough to apply properties to specs because you know you have to add it to the builder (if there is one) and the subsequent request object. But since nowhere part of this chain is the single property method required it can be quite easy to miss.

I am just not a fan of adding code for the sake of code just to shave off a few characters that doesn't even save line count. And that 3 line utility method must become 10 or so to include associated Javadocs.

And we shouldn't force users to learn more than they should. Adding another convention into the mix does no one favors.

**Comment by JamesGallicchio** [comment]
I’d second Dan’s comment here. __Concise__ code is not always __short__ code. From a user’s perspective, yes, this adds a few characters, but if it bugs them that much, then they can make a utility for themselves.

I don't even really think these are utility methods.

Look at the permissions utilities. There's plenty of reason to have them:
1) It's part of Discord's spec
2) It's nontrivial code
3) It's all contained in a static utility class with just a couple methods in entity classes for interfacing with that static utility class. It's relatively little code

Now compare that to these proposed  single param methods
1) It is more intuitive for beginners to use without questions if they don't read the documentation, I think? (which is most beginners)
2) It saves a few characters for some use cases?
3) ???

They're not utility methods. They're aliases or shortcut methods. What they're aliasing isn't complicated to remember or even especially verbose. It's just a bit of new syntax for people to learn.

 I think more than anything these alias methods would simply be connecting "how it works in the Discord client" to "how it works in the Discord API." For example, in the Discord client, sending messages is almost always just sending text. Yes, you can send other stuff, but the "default" is to just send content. That's not how the Discord API works; there's nothing particularly special about content when creating a message. If you sent the endpoint nothing but a string, it wouldn't assume you wanted to create a message with the string as its content.

Similarly, nicknames are just a click and edit situation in the client. But it's not the same in the API; you're sending a member update that specifies to change the nickname.

Given the previous point, if we want a measure for determining where to stop with the alias methods, then maybe we can utilize the Discord client to determine what people would expect the API to make easy. "If I can add a channel or edit a nickname or send a message in one click, then I should have an alias to do that too" kinda mentality.

But, again, I'd oppose adding any on the basis that it's not clean and that I don't see the benefits. It's literally just bloat. I'm admittedly curious just how many lines would be added, so if someone wants to PR it I'd certainly be interested.

**Comment by danthonywalker** [comment]
The problem with that is the client is more volatile to change than even the API. I'm not entirely opposed, but I do take it as a warning.

As for line count, because these are alias methods as you call them, they are at least 3 lines without Javadocs. So taking into account *just* edit specs, there is 36 properties so that would be 108 lines. With Javadocs which, taking the number of lines associated with MessageChannel#createMessage(String), which is 10 lines, so with Javadocs that is 13 lines per method or 468 lines in total.

With create specs, I think all of them have a "one property is required the rest are optional" situation, like MessageCreateSpec, except EmbedCreateSpec, where every field is optional, so that would be another 9 methods, so another 117 lines.
