### ISSUE TITLE
Get last heartbeat time

### ISSUE THREAD

**Issue by GrandPanda** [Discord4J/Discord4J#462]
**Feature Description:** 
The ability to obtain the time between the last heartbeat and heartbeat ack on the gateway.

**Justification:** 
This can be useful for diagnostic purposes and was [present in v2](https://github.com/Discord4J/Discord4J/blob/master/src/main/java/sx/blah/discord/api/IShard.java#L96-L101).

**Comment by koyagami** [comment]
I agree with this. Most other frameworks provide us with this value directly, and being java, it is a bit of a pain to try and expose this another way. Currently I am having to re-implement the entire DiscordClient, the entire ServiceMediator, and override the GatewayClient just to expose this method, which is not that great, and leaves a large amount of boilerplate code that wouldn't be needed if this was just made public :)

**Comment by danthonywalker** [comment]
As stated, there is more accurate ways to measure ping. To users of your bot, ping is the delay between when they execute a command and when the bot responds. A heartbeat measurement is not indicate this at all, it only indicates the ping between a gateway send and a respective gateway response which is not equal to the flow of execution that I just stated.

I am not comfortable opening up internals to end-users just for this specific purpose. An API is much easier to open up as needed, but is impossible to close what it shouldn't (unless you want to break backwards-compatibility). More exposed internals just leads end-users confused on how to navigate the API and lets them break stuff that wouldn't be possible either wise (of course, you could use reflection, but you're already agreeing to breaking stuff at that point).

Thus, if you *really* want this then I suggest either/or 2 changes to `core`.
1) Have "safe" internals, like how Java 9 made some sun.misc.Unsafe functionality part of the JDK API itself and exposes it in a safe manner.
2) Move things users shouldn't touch to a specific `internal` package hierarchy. This would require making all such classes public and their respective constructors since `core` needs to be able to access and construct these objects externally. Things inside this package are deemed "unsafe" and we as a library are free to change the APIs at any point while maintaining our versioning scheme. I don't particularly like this only because `gateway` and `rest` are APIs in of themselves, thus there isn't much "internals" to `core`, which still allows users to shoot themselves in the foot, so to speak. However, the `internal` declaration can just be an indication of accessing unsafe resources, but this isn't nearly as clear as it just being impossible to access at all.

So overall, I'm not convinced.

**Comment by quanticc** [comment]
Added the value to gateway because I realized it needs this value to detect a connection missing ACKs.
https://github.com/Discord4J/Discord4J/blob/f0645ad5ff341bb04441ff1ca73cd545f235f012/gateway/src/main/java/discord4j/gateway/GatewayClient.java#L182

@koyagami you should be aware that you are only measuring the gateway heartbeat response and like it was said above, it is unrelated to REST responses.

I hope we can discuss how are internals exposed through core in a separate ticket as v3 reaches feature parity.

**Comment by quanticc** [comment]
Closing via f0645ad and 8690f37
