### ISSUE TITLE
Executing Webhooks

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#547]
**Feature Description:** 
Add the ability to execute webhooks.

**Justification:** 
This is a very frequently requested feature. Our reasoning for not including it (both in v2 and v3) is that Discord4J is meant to be for bots and webhooks are not meant to be used by bots but by automated external services. While I still stand by the idea that bots executing webhooks are abusing the feature, I don't think we can justify this omission any longer, especially while other libs have the feature. 

Executing webhooks is more than just "make an http request" for two reasons:
1. You must handle ratelimiting
2. People want to use `core` types

We already have all of the infrastructure in place to meet these goals. It would be trivial to add:
`WebhookExecutionService <: discord4j.rest.service.RestService`
`WebhookExecutor#execute(Webhook, spec)`

In my opinion, the only question is regarding where this functionality will live. `Webhook#execute()` would be obvious, but I'm still clinging on, at least a little, to the idea that this doesn't belong directly in Discord4J. Perhaps a separate repo under the D4J org?

**Comment by j0rdanit0** [comment]
I hope this is added as well. My main reason for executing webhooks from a bot is because webhooks allow sending multiple Embed objects, but a regular message does not. Sending multiple Embed objects through the webhook greatly reduces the number of calls I would otherwise have to make through the bot to send all the Embeds through. And if that could be done within the D4J framework, all the better for me. :)

**Comment by SizableShrimp** [comment]
I think a separate repository would be fine. I understand the premise of Discord4J being a 1:1 Discord API wrapper, but in this separate repository other util things that would be nice to have and highly requested could be added so that the core idea of Discord4J is maintained. If anything else arises, things could be added to make the life of developers with the library much easier. Take a look, for example, at [JDA Utils](https://github.com/JDA-Applications/JDA-Utilities). While I don't agree with the code or design, I believe some of the util they provide is very helpful especially for beginners in Java. Now, the team behind Discord4J definitely doesn't have to something to this extent. However, maybe this separate repo could be a house for something similar in the future and even better to be made by the team behind Discord4J instead of an external source like JDA Utils is. I believe starting small with this feature and any others is a good starting place, and would be nice to have.

**Comment by GreemDev** [comment]
D4J already has a, although experimental, command system built-in which is useful to reduce the use of if-else command handling in event listeners; however maybe a separate, super robust library could be included in this DJ4-Addons (or something named that) repository. Something like that I'd love to contribute to.
