### ISSUE TITLE
Transition to immutable Specs

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#585]
In order to provide a safe way to do Specs without requiring the Consumer approach. We can migrate our Specs to an immutable builder style.

The end goal is to provide reusable instances.

**Comment by quanticc** [comment]
I have edited this ticket's title.

@danthonywalker What do you think if after making specs immutable we could re-add non-consumer parameters like `setEmbed(EmbedCreateSpec)` ?

**Comment by danthonywalker** [comment]
I don't see a reason why not.

**Comment by darichey** [comment]
Can we sketch what this looks like?

**Comment by quanticc** [comment]
@darichey 

```java
public class MessageCreateSpec implements Spec<MultipartRequest> {

    private final String content;
    private final String nonce;
    private final boolean tts;
    private final EmbedData embed;
    private final List<Tuple2<String, InputStream>> files;
    private final AllowedMentionsData allowedMentionsData;

    // Example factory
    public static MessageCreateSpec create() {
        return new MessageCreateSpec(null, null, false, null, null, null);
    }

    /** Copy constructor */
    MessageCreateSpec(String content, String nonce, boolean tts, EmbedData embed, List<Tuple2<String,
            InputStream>> files, AllowedMentionsData allowedMentionsData) {
        this.content = content;
        this.nonce = nonce;
        this.tts = tts;
        this.embed = embed;
        this.files = files;
        this.allowedMentionsData = allowedMentionsData;
    }

    // create a new immutable instance on property change
    public MessageCreateSpec setContent(String content) {
        return new MessageCreateSpec(content, this.nonce, this.tts, this.embed, this.files, this.allowedMentionsData);
    }
    
    // ...
    
    // asRequest stays as is.
}
```

**Comment by darichey** [comment]
Thanks, I'd like to take this.

**Comment by darichey** [comment]
There's a few issues here where the path forward isn't clear, particularly regarding making certain fields immutable. 

**1. `ImmutableX.Builder`**

A lot of specs are currently essentially just wrappers around `ImmutableX.Builder`, serving mostly to just translate from higher-level types (e.g., `Snowflake -> String`). These builders are obviously mutable, so we need to move away from them if immutability is our goal. 

The first solution I can think of for this is to simply copy up the fields from the builder with the higher-level types and just call to the builder in `asRequest()`. This would be straightforward, but it's an unfortunate amount of code which is *almost*-duplicate.

Another solution could be enabling [copy methods](https://immutables.github.io/immutable.html) on `ImmutableX`. This would allow the spec to start with `ImmutableX.builder().build()` and each `setY` method would return a new spec with `immutableX.withY(y)`.

**2. Collections fields**

We have a couple of specs like `EmbedCreateSpec` which have mutable collections in them. It wouldn't be so bad if we just had `setFields(List<EmbedFieldData>)`, but we also have provided convenience methods like `addField(EmbedFieldData)` which I think we should aim to keep.

Java isn't going to help us here, and I can't think of a good solution at the moment.

**Comment by quanticc** [comment]
We should enable copy methods for the first item you mention.

About collection fields, the convenience methods are very useful to reduce verbosity from the user standpoint so I think we should keep them. What are your concerns about going that route?

**Comment by danthonywalker** [comment]
I am still in a mindset of if we're trying to make rest and gateway modules more user accessible and more exposed through core then maybe we stand to benefit of, like how we have been eliminating intermediary data classes, of eliminating the layer between Spec and Immutables builder.

Specs offer us high level abstractions like Snowflake <-> String, why can't we just tell Jackson to serialize it as such?

If we could make the builders Immutable I don't see much need of needing the spec layer.

**Comment by Alex1304** [comment]
Hey, may I come up with a proposal to make those immutable specs not a pain to implement while (hopefully) solving all of the issues we've been facing regarding their design?

Ok so, my idea would be basically to use the [Immutables library](https://immutables.github.io) for specs just like we did for immutable json objects, and leverage some of its advanced features to achieve our goals and proposing something that is really flexible and user friendly.

I've been playing around with Immutables for a while and came up with something like this:

```java
// SpecStyle.java

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
@Value.Style(
        typeImmutable = "*",
        visibility = Value.Style.ImplementationVisibility.PUBLIC,
        allMandatoryParameters = true
)
public @interface SpecStyle {}
```

```java
// MessageCreateSpec.java

@SpecStyle
@Value.Immutable
interface AbstractMessageCreateSpecTemplate extends SpecTemplate<MultipartRequest<MessageCreateRequest>> {

    Optional<String> content();

    Optional<String> nonce();

    @Value.Default
    default boolean tts() {
        return false;
    }

    Optional<EmbedCreateSpecTemplate> embed();

    @Value.Default
    default List<Tuple2<String, InputStream>> files() {
        return Collections.emptyList();
    }

    Optional<AllowedMentions> allowedMentions();

    Optional<Snowflake> messageReference();

    @Override
    default MultipartRequest<MessageCreateRequest> asRequest() {
        MessageCreateRequest json = MessageCreateRequest.builder()
                .content(content().map(Possible::of).orElseGet(Possible::absent))
                .nonce(nonce().map(Possible::of).orElseGet(Possible::absent))
                .tts(tts())
                .embed(embed().map(EmbedCreateSpecTemplate::asRequest).map(Possible::of).orElseGet(Possible::absent))
                .allowedMentions(allowedMentions()
                        .map(AllowedMentions::toData)
                        .map(Possible::of)
                        .orElseGet(Possible::absent))
                .messageReference(messageReference()
                        .map(ref -> Possible.of((MessageReferenceData) MessageReferenceData.builder()
                                .messageId(ref.asString())
                                .build()))
                        .orElseGet(Possible::absent))
                .build();
        return MultipartRequest.ofRequestAndFiles(json, files());
    }
}

@SpecStyle
@Value.Immutable(builder = false)
interface AbstractMessageCreateSpec extends AbstractMessageCreateSpecTemplate {

    MessageChannel channel();

    default Mono<Message> asMono() {
        return channel().createMessage(MessageCreateSpecTemplate.copyOf(this));
    }
}
```

It introduces two concepts: **Specs** and **Spec Templates**.

The interfaces above are package-private and prefixed with `Abstract*`, we apply a style that generates the implementations in a such way that their name is just `X` instead of `ImmutableX` and set visibility to public. The justification for this choice is that the implementation class, unlike the interface, exposes copy methods (methods prefixed by `with*`), and also it makes the API more simple on the user standpoint since there is no longer the distinction `X` vs `ImmutableX` (the former being package-private and the latter being renamed to just `X`). You can also notice that there are two interfaces in the same .java file and that the filename is different than the interface names, this is possible because everything is package-private.

We have a first interface `XSpecTemplate` that extends `SpecTemplate<T>` which is essentially the same thing as the current `Spec<T>` interface (defines a single `T asRequest()` method). Our `XSpecTemplate` is in charge of declaring the attributes of the spec (they are all either `Optional` or `@Value.Default`), and implementing `asRequest()`. Users will be able to construct an instance of it using the generated builder, and derive existing instances using the copy methods:

```java
template1 = MessageCreateSpecTemplate.builder().setContent("hello").build();

template2 = template1.withEmbed(EmbedCreateSpecTemplate.builder().setXxx(...).build());

Message message = channel.createMessage(template2).block();
```

On the other hand, we have a second interface called just `XSpec` that extends the first one (`XSpecTemplate`). This one will be useful to get something that is closer to what imagined @darichey initially with his Mono-based specs:

```java
Message message = channel.createMessage()
        .withContent("content")
        .asMono().block()
```
It could theoretically extend `Mono<Message>` directly if we make it an abstract class instead of an interface, but it causes bugs with the Immutables library as explained in this issue: https://github.com/immutables/immutables/issues/1147, so I resorted to use an extra `.asMono()` instead.

`MessageChannel` would now be implemented as follows, allowing for both approaches:

```java
public MessageCreateSpec createMessage() {
    return MessageCreateSpec.of(this);
}

public Mono<Message> createMessage(MessageCreateSpecTemplate template) {
    return Mono.defer(
                () -> {
                    MessageCreateSpecTemplate actualTemplate = getClient().getRestClient()
                            .getRestResources()
                            .getAllowedMentions()
                            .map(allowedMentions -> (MessageCreateSpecTemplate) MessageCreateSpecTemplate.builder()
                                    .from(template)
                                    .allowedMentions(allowedMentions)
                                    .build())
                            .orElse(template);
                    return getRestChannel().createMessage(actualTemplate.asRequest());
                })
                .map(data -> new Message(getClient(), data));
}
```
 I didn't put the `createMessage(String)` variant but you got it I guess.

To conclude, I believe this solution to be beneficial in that the user would have the choice between regular Builder pattern vs copy methods, as well as the choice between a separate template object vs a one-liner. It would be also beneficial on our end because the use of Immutables would save us from tons of boilerplate/duplicate code and we can keep something easy to maintain.

**Comment by darichey** [comment]
Overall, I like the approach. I have a few comments below.

1. Moving Immutables up in to Discord4J directly is a "big" change that we should be careful about. Let's make sure that the build process is something we can support widely. For example, someone mentioned that it might not work in Eclipse. Also, we have already been unable to build discord-json with javac 8, so we would need to move to 11 (still with source and target 8 for now, of course). 

2. I think we will have to use `Possible` instead of `Optional` to allow for nullable fields (e.g., resetting a nickname or removing someone from a voice channel). This shouldn't be a problem as @quanticc has already built support for `Possible` encoding in discord-json ([link](https://github.com/Discord4J/discord-json/blob/bb804e5a39852e293ebab411922fc950b5a6f1bc/encoding/src/main/java/discord4j/discordjson/possible/PossibleEncoding.java#L41-L61))

3. The `asRequest` implementation is unfortunately little ugly. Not sure if there is much we can do here. I had the idea that maybe we could go even further with code generation and automatically derive specs from `XRequest` classes in discord-json, but it turns out that this would only directly apply to about half of existing specs. See the following table.

	  <details>
	  <summary>Table of specs and what they build (i.e., the T of Spec&lt;T&gt;)</summary>
	  
	  | Spec                                       | Builds                                    |
	  ---------------------------------------------|-------------------------------------------|
	  | `AuditLogQuerySpec`                        | query string                              |
	  | `BanQuerySpec`                             | query string                              |
	  | `GuildPruneCountSpec`                      | query string                              |
	  | `GuildPruneSpec`                           | query string                              |
	  | `MessageCreateSpec`                        | `MultipartRequest<MessageCreateRequest>`  |
	  | `WebhookExecuteSpec`                       | `MultipartRequest<WebhookExecuteRequest>` |
	  | `VoiceChannelJoinSpec`                     | voice channel join logic                  |
	  | `CategoryCreateSpec`                       | `ChannelCreateRequest`                    |
	  | `CategoryEditSpec`                         | `ChannelModifyRequest`                    |
	  | `NewsChannelCreateSpec`                    | `ChannelCreateRequest`                    |
	  | `NewsChannelEditSpec`                      | `ChannelModifyRequest`                    |
	  | `StoreChannelEditSpec`                     | `ChannelModifyRequest`                    |
	  | `TextChannelCreateSpec`                    | `ChannelCreateRequest`                    |
	  | `TextChannelEditSpec`                      | `ChannelModifyRequest`                    |
	  | `VoiceChannelCreateSpec`                   | `ChannelCreateRequest`                    |
	  | `VoiceChannelEditSpec`                     | `ChannelModifyRequest`                    |
	  | `EmbedCreateSpec`                          | `EmbedData`                               |
	  | `InteractionApplicationCommandCallbackSpec`|`InteractionApplicationCommandCallbackData`|
	  | `MessageReferenceSpec`                     | `MessageReferenceData`                    |
	  | `GuildCreateFromTemplateSpec`              | `TemplateCreateGuildRequest`              |
	  | `GuildCreateSpec`                          | `GuildCreateRequest`                      |
	  | `GuildEditSpec`                            | `GuildModifyRequest`                      |
	  | `GuildEmojiCreateSpec`                     | `GuildEmojiCreateRequest`                 |
	  | `GuildEmojiEditSpec`                       | `GuildEmojiModifyRequest`                 |
	  | `GuildMemberEditSpec`                      | `GuildMemberModifyRequest`                |
	  | `GuildTemplateCreateSpec`                  | `TemplateCreateRequest`                   |
	  | `GuildTemplateEditSpec`                    | `TemplateModifyRequest`                   |
	  | `InviteCreateSpec`                         | `InviteCreateRequest`                     |
	  | `MessageEditSpec`                          | `MessageEditRequest`                      |
	  | `RoleCreateSpec`                           | `RoleCreateRequest`                       |
	  | `RoleEditSpec`                             | `RoleModifyRequest`                       |
	  | `UserEditSpec`                             | `UserModifyRequest`                       |
	  | `WebhookCreateSpec`                        | `WebhookCreateRequest`                    |
	  | `WebhookEditSpec`                          | `WebhookModifyRequest`                    |
	  | `WebhookEditWithTokenSpec`                 | `WebhookModifyWithTokenRequest`           |
	  </details>

	That approach would not apply to the specs at the top, those which build query strings, multipart request, etc.. There would also need to be some special consideration for the channel specs which all produce `Channel{Create|Modify}Request` but only expose subsets of those fields. Anyways, I'm ranting now, but I wanted to drop the info/idea here while I was thinking about it. Ultimately, this leads into my next point...

4. Let's keep it simple. The ability to do the #693-style specs is great, but let's leave it for later. This change has taken far too long to get done, because I keep trying to do something too big with it (like we could do with the previous point). Of course, let's not paint ourselves into a corner where we _couldn't_ do that eventually, but let's keep it simple for now. 

5. We need to consider how this will affect the existing spec methods, `doX(Consumer<? super DoXSpec>)` and the migration path around them. Will 3.2 leave them untouched? Deprecated? If so, we may have naming issues.

Again, I like the approach overall. Would you like to start on it?

**Comment by Alex1304** [comment]
Sure, I'll take your comments into consideration and make a draft PR to continue the discussion further 🙂
