### ISSUE TITLE
Voice session description sometimes gets stuck in an infinite loop

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#633]
**To Reproduce:** This issue cannot be reproduced consistently, it happens when the bot has trouble connecting to the voice channel.

**Expected Behavior:** The bot fully connects or gets disconnected with a way to detect that something went wrong.

**Actual Behavior:** The bot gets stuck in an infinite connection loop. https://pastebin.com/kvTYVFf9

**Version:** 3.1.0-SNAPSHOT

**Other:** In the client, the bot is shown has logged in the voice channel.

**Comment by Lyrth** [comment]
Able to reproduce consistently, seems that this happens when the bot has trouble connecting to the voice server, e.g. it takes too long to respond. By redirecting the connection elsewhere, for example to loopback in Windows:

`netsh int ip add address "Loopback" 108.61.yyy.zzz`

(The IP address is the one the bot tries to connect to, shown in `discord.voice.VoiceSocket` logs)
This simulates a network issue connecting to the voice server. Result is [this similar log](https://gist.github.com/Lyrth/4eb9f14574d22418b60ec010c8355dc3).

[This method](https://github.com/Discord4J/Discord4J/blob/master/voice/src/main/java/discord4j/voice/VoiceSocket.java#L80) in VoiceSocket might be something to look into.

**Comment by Shadorc** [comment]
This can also be reproductible by setting a default wrong address instead of the `address` field here: https://github.com/Discord4J/Discord4J/blob/master/voice/src/main/java/discord4j/voice/VoiceSocket.java#L57

**Comment by quanticc** [comment]
We should add a configurable Spec then

**Comment by quanticc** [comment]
a RetrySpec to define the strategy to perform IP discovery. If it fails, change the implementation so it can close and release resources-
