### ISSUE TITLE
Event classes should hold their dispatches

### ISSUE THREAD

**Issue by ByteAlex** [Discord4J/Discord4J#698]
**Feature Description:** 
Event-classes should hold their dispatch-json in it
E.g. GuildCreateEvent should hold a GuildCreate(Data) in it, which can be accessed via getData()

**Justification:**
My use case for this is the combination of redis store and the requirement to build a custom cache with one users mutual guilds.
To avoid looping on all guilds, I need to check MemberAdd, MemberLeave, GuildCreate and GuildDelete.
On the GuildCreate I just receive the plain Guild object, which has the option to get members via .getMembers(), though this method has N redis calls behind it, with N being the number of members.
I just need the member id for storing in the cache, so why would I need to iterate calls on the redis to get the member list?
When I have the dispatch available I can just loop on that *local* list to get the member-ids and then store them in a list in redis for my custom cache.

**Comment by quanticc** [comment]
I think you could explore delegating our default `DispatchEventMapper` to inject custom capabilities and you can derive extended versions of `Event` holding the data from it.

I might add a code example later

**Comment by ByteAlex** [comment]
Why would it be bad to give access to the dispatches?
I don't see a loss of anything in that, or is there any?

**Comment by danthonywalker** [comment]
Because we are bleeding practically useless data to the core of our API that most users use. It's polluting the API space for our users for no benefit to almost every one of them.

Here is my personal opinion. A lot has been adjusted for D4J to accommodate your use cases. Which is fine, we want our API to be flexible enough to handle practically any use case for any bot large or small. However, there comes a point where we're adding things into the library that *only* work for your use cases rather than working with the systems we have to implement them yourself.

That is partially why we have `connect`. As far as I'm aware you're the only one to utilize it. That repo is what should hold the "my bot needs really weird things so I want abstractions on top of the D4J API to do them". I feel this is definitely a candidate for that instead of it bleeding into our core API.

**Comment by quanticc** [comment]
Let's see if our current API can work with this. Besides trying the custom mapper implementation, we have our Store API that could use some improvements for the Redis implementation so you don't have to make superflous calls to it.

For example why not thinking about a Store that can cache in-memory a part of the values, maybe under some Predicate.

At least until we can find a better structure to hold our redis data (Sorted set instead of plain hash+json value, ...)

**Comment by ByteAlex** [comment]
I've been testing with a store-impl which I called "DelegatingCacheStore" Caches or delegates to another store, with redis impl, and that seems to work nice though.
Anyhow I'm also open to test that EventDispatchMapper thingy.
Is there any kind of documentation of how to use it properly?
The only thing I made with that yet, is disabling it for a part of my architecture.

**Comment by quanticc** [comment]
Nice, let us know if it's good because we're currently discussing with @danthonywalker potential improvements to how we layout our data in redis.

Regarding the mapper impl, I'll add a proof of concept here soon

**Comment by quanticc** [comment]
Follow up on this issue: while the current API makes it possible, it involves quite a long process of creating a custom DispatchEventMapper class and also producing an alternative Event class to hold that Dispatch.

```java
GatewayDiscordClient client = DiscordClient.create(System.getenv("token"))
        .gateway()
        .setDispatchEventMapper(new DispatchEventMapper() {

            private final DispatchHandlers defaults = new DispatchHandlers();

            @Override
            public <D, E extends Event> Mono<E> handle(DispatchContext<D> context) {
                // can access dispatch
                return defaults.handle(context);
                // but it's not so simple to include it here
            }
        })
        .login()
        .block();
```

We can revisit this after 3.1 release to explore ways of making this more open for customization.

**Comment by quanticc** [comment]
Scheduling this for next 3.1, there are other use cases where this would be useful, like working with a noop cache and the current workaround (accessing raw dispatch flux) is not very friendly.

**Comment by Shadorc** [comment]
If the event classes hold their own dispatch, they no longer need to have a constructor taking all the fields individually but maybe this behavior should be kept.  
Which of these approach should be implemented:
```java
public TypingStartEvent(GatewayDiscordClient gateway, ShardInfo shardInfo, TypingStart dispath, long channelId, @Nullable Long guildId, long userId, Instant startTime, @Nullable Member member) {
```
or
```java
public TypingStartEvent(GatewayDiscordClient gateway, ShardInfo shardInfo, TypingStart dispath) {
```
or maybe a mix between values that can be easily retrieved vs values that are computed
```java
public TypingStartEvent(GatewayDiscordClient gateway, ShardInfo shardInfo, TypingStart dispath, @Nullable Member member) {
```
