### ISSUE TITLE
CloseStatus not propagated when unrecoverable

### ISSUE THREAD

**Issue by gmt2001** [Discord4J/Discord4J#711]
When Discord reports a connection/identification error by using a close code that is considered unrecoverable, such as `4014 Disallowed intent(s)`, Discord4J emits this back to the client class as just a plain old `DISCONNECT` event without any information on what close code was actually returned. This is in contrast to any other close code which will usually emit a CloseException.

This occurs because `handleClose` returns just the close code, but does not emit an exception, when one of these unrecoverable close codes are encountered. 

**To Reproduce:** Using a token that has the `Presence Intent` toggle set to _Disabled_ in the Developer Dashboard.

```
DiscordClientBuilder builder = DiscordClientBuilder.create(token);
DiscordClient client = (DiscordClient) DiscordAPI.builder.build();
client.gateway().setEnabledIntents(IntentSet.all()).login().timeout(Duration.ofSeconds(30))
    .doOnError(e -> {
        // Never fires for 4014 Disallowed intent(s)
        System.err.println("Failed to authenticate with Discord: [" + e.getClass().getSimpleName() + "] " + e.getMessage());
    }).doOnSuccess(cgateway -> {
        System.out.println("Connected to Discord");
    }).subscribe();
```

**Expected Behavior:** Discord4J should either emit a close code in some way when the close code is in the `nonRetryableStatusCodes` List, or provide a method to retrieve the last close code.

**Actual Behavior:** Discord4J does not make the close code or anything that can be used to derive it available to the user or the developer, unless Reactor logging is used and monitored

**Version:** 3.1.0.M2

https://github.com/Discord4J/Discord4J/blob/a74ce210dc0a5263aafb23fc21a3cbe189646d20/gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java#L344-L351

https://github.com/Discord4J/Discord4J/blob/a74ce210dc0a5263aafb23fc21a3cbe189646d20/gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java#L379-L418

**Comment by quanticc** [comment]
Thanks for opening this issue! Good timing though as it involves some return type changes and we can manage to get some things done in before 3.1

I'm going to work on it, maybe mirror changes to voice module as well.

This should be done in stages:
- Return error status codes through an error `Mono`
- Expose `CloseStatus` through the `GatewayClient` API
- Forward an early error through `GatewayDiscordClient::login`, provided `awaitConnections` is `true`. Otherwise we immediately complete the `Mono` and your example wouldn't be possible even after this change. You'd still be able to read the close code if you directly access the GatewayClient.
- Consider to return at least one `CloseStatus` through `GatewayDiscordClient::onDisconnect`

**Comment by quanticc** [comment]
Some notes about implementation:

- For normal gateway, we will route non recoverable status codes as a CloseException through `execute` and `close`
- Decided not to change the signature of these two `Mono<Void>` methods: it's beyond what this ticket seeks which is exposing the **error** cases
- Startup unrecoverable errors should be exposed through the `login()` method and friends, even if disabling `awaitConnections` so your OP example code should work in either case
- Decided not to expose a method for retrieving the `CloseStatus`. Instead, the `close` method is equipped to return the original signal. This should work as `DefaultGatewayClient` is not reusable (code was added to enforce this)
- Mirrored most changes to the voice gateway implementation
