### ISSUE TITLE
Bot disconnects in voice channels when run on hosted instances

### ISSUE THREAD

**Issue by privisi** [Discord4J/Discord4J#752]
I have encountered an issue with my discord bot joining / maintaining a connection with a voice channel when the bot is on a hosted instance (Such as  ec2 or vultr). When I host it locally, this issue does not occur.

**To Reproduce:**
1. Create a music bot following the tutorial: https://github.com/Discord4J/Discord4J/wiki/Music-Bot-Tutorial (The Discord4J 3.1.x - Imperative Approach was used in my instance)
2. Build and deploy the bot in an instance (I have tried ec2 and vultr and deployed it using: java -jar as a test)
3. Issue the !join command, the bot should join the channel and then disconnect after about 10 seconds.

**Expected Behavior:** Bot joins the voice channel

**Actual Behavior:** Bot joins the voice channel but disconnects after 10 seconds.
Stack trace and logs from when the !join command is issued (discord4j.voice set on DEBUG):
```
07:51:04.051 [d4j-events-3] DEBUG d.c.event.ReplayingEventDispatcher - Subscription 18e80174 to VoiceStateUpdateEvent created
07:51:04.052 [d4j-events-3] DEBUG d.c.event.ReplayingEventDispatcher - Subscription 3f331d76 to VoiceServerUpdateEvent created
07:51:14.040 [parallel-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription 18e80174 to VoiceStateUpdateEvent disposed due to cancel
07:51:14.048 [parallel-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription 3f331d76 to VoiceServerUpdateEvent disposed due to cancel
07:51:14.060 [d4j-events-3] DEBUG d.c.event.ReplayingEventDispatcher - Subscription 747f281 to MessageCreateEvent disposed due to cancel
07:51:14.065 [d4j-events-3] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
        at reactor.core.Exceptions.propagate(Exceptions.java:393)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Mono.block(Mono.java:1666)
        at marklil.App.lambda$main$2(App.java:72)
        at marklil.App.lambda$main$4(App.java:103)
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
        at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onNext(FluxFilter.java:240)
        at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$DisposableWorkerTask.run(ForkJoinPoolScheduler.java:443)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker.processTaskQueue(ForkJoinPoolScheduler.java:407)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
```

**Version:** 3.1.0

**Other:**
- Version 1.3.50 of the Lavaplayer was used
- Application was built and compiled in java 1.8
- Bot was hosted on ubuntu 18.04
- Firewall was disabled and all inbound and outbound traffic set to be allowed on all ports on vultr

**Comment by quanticc** [comment]
Since your logs don't show any discord4j.voice lines, I believe it is timing out before we can grab the actual error.

Can be a DNS issue, etc. so to know more details could you increase the timeout to, let's say, 1 minute?

```java
channel.join(spec -> spec.setProvider(provider)
        .setTimeout(Duration.ofMinutes(1)))
        .block();
```

For comparison this is what a successful join looks like with debug logs: https://gist.github.com/quanticc/4cfeb59f34e105fd279a7279c12796ec

**Comment by privisi** [comment]
I've set the timeout to one minute but that made no difference. The same logs were outputted.

**Comment by baskwo** [comment]
Hi, today my bot did the exact same error and when that happen it makes the whole event dispatching fail. Like if something was waiting for the Mono/Flux to end.

Something I saw is that when this timeout thing occurs, it's because discord takes quite long to establish the connection. Sometimes I might get a "No route" from discord as the connection status.

I tried few things on my end like :
* using onErrorResume
* using doOnError
* increasing the timeout like you said earlier

But nothing worked so I started to check the Discord API Documentation.
[Here](https://discord.com/developers/docs/topics/voice-connections#resuming-voice-connection) it says that when we try to reconnect to a voice channel and it's unsuccessful, we must reconnect. Is this what Discord4J do? I don't have much time tonight, but I'll try to dig up the more tomorrow or during the weekend.

**Comment by quanticc** [comment]
Hey there. trying to reproduce locally and I can't find a reliable method yet to trigger this, however, I think retrying has an issue currently which I'm going to look into first.

I plan on adding more debugging information to the voice handshake to detect how far into it you get until it times out.

Right now there is debug info with the discord4j.voice and reactor.netty loggers but it's not enough.

**Comment by baskwo** [comment]
I'll try something to reproduce it.
But I think you can reproduce it by doing a "Thread.sleep()" in one of the flatmap?
Or maybe flatmap(item -> Mono.error(new TimeoutException())?

**Comment by quanticc** [comment]
Currently testing with https://jagt.github.io/clumsy/ for some bad network scenarios.

I'm preparing some changes to ideally support retrying a voice channel join request because right now we have some issues with either resuming or dropping the attempt to allow an external retry.

Could you tell us the code you're using atm to join a vc ? currently rolling this

```java
Mono<Void> join = client.getEventDispatcher().on(MessageCreateEvent.class)
        .filter(e -> e.getMessage().getContent().equals("!join"))
        .flatMap(e -> Mono.justOrEmpty(e.getMember())
                .flatMap(Member::getVoiceState)
                .flatMap(VoiceState::getChannel)
                .flatMap(channel -> channel.join(spec -> spec.setProvider(provider)))
                .retryWhen(Retry.backoff(3, Duration.ofSeconds(2))) // optional
                .doFinally(s -> log.info("Finalized join request after {}", s))
                .onErrorResume(t -> {
                    log.error("Failed to join voice channel", t);
                    return Mono.empty();
                }))
        .then();
```

**Comment by baskwo** [comment]
Clumsy might work yeah!

The code I'm using is this https://gist.github.com/baskwo/ff419fb5ad40aeabb76a72d63d3b139a

I'm using Spring boot with a Reactive Web Server + I made a custom SourceManager, SeekableInputStream and AudioTrack for ClassPathResources

**Comment by quanticc** [comment]
Can you try with the latest `3.1.2-SNAPSHOT` ? I've improved the handling on some disconnection cases, resume works properly and added more logging events.

if you turn up debug logs for `discord4j` and `reactor.netty` I would be able to investigate properly. Mostly looking to identify how far into the handshake can you get.

**Comment by baskwo** [comment]
So I installed locally the branch 3.1.x to get the version 3.1.2-SNAPSHOT.
As the Discord Servers right now are fine, I used Clumsy to put the lag at 3000ms and here's what it did.

1. I connect to voice channel
2. After few seconds bot join the same channel (as expected)
3. Do nothing until the 10s mark and then throw the TimeoutException
4. Few seconds later it disconnects from the voice channel
5. I leave and the reconnect to the voice channel
6. Bot does nothing

Here's the log with discord4j on DEBUG level.
https://gist.github.com/baskwo/ec1c503437896d87f8085631bcd725ba

**Comment by baskwo** [comment]
I added a log in the discord4j.voice.DefaultVoiceGatewayClient#connect everytime we receive a voice payload.
I received Hello and Ready then nothing else.

**Comment by quanticc** [comment]
Definitely some NAT or firewall getting in the way if IP discovery is failing. The log lines that are missing are "Voice socket setup complete" and finally "Receiving events".

The behavior between your steps 1-4 is consistent if I block UDP packets with clumsy.

It is also expected that if a timeout happens, the `join` sequence emits an error, so no retries are attempted at this stage. This can be countered by applying one of the `retry` or `retryWhen` operators.

Focus should be trying to solve the firewall issue, so UDP packets can flow

**Comment by baskwo** [comment]
I don't think in this case it's a NAT/firewall issue. 
If I remove the 3000ms lag everything is smooth right now (even with version 3.1.1) but when I add a bit of lag (like I was experiencing few days ago like 100ms) it starts to do the same thing. 

I did a few debugging and I've found the VoiceSocket doesn't even have the time to start connecting.
In the VoiceSocket I added a line .doOnConnect which is called at the start of connecting and in the logs it appeared after the timeout which is normal because it's called onSubscribe but I never saw the "Connected to" log.

I understand that it's normal to timeout in this case but the real problem is that it's "blocking" the client which makes it to not process any more event (not sure if it receives it or not yet)

**Comment by quanticc** [comment]
If the issue is pure latency, try increasing the discovery timeout in the join spec, then: `setIpDiscoveryTimeout(Duration)`. It's 5 seconds by default.

Might also need to give more headroom by increasing the overall timeout with `setTimeout`.

**Comment by baskwo** [comment]
Yes increasing the timeout helps it to work under high latency but I don't think it's a viable solution. I'd rather see the timeout exception that tells me the discord API is having trouble than the bot not working anymore.

If we/you could find a way to make the bot works after a timeout exception it would be the best solution for everyone in my opinion.

**Comment by quanticc** [comment]
If discovery fails (due to timeout or being unable to route) no voice comm can happen. To make it work even after a timeout, the join request must be retried for a new handshake, like the example I posted earlier: https://github.com/Discord4J/Discord4J/issues/752#issuecomment-695149176

Once a `VoiceConnection` has been established, it should be able to resume on network issues. If the session is invalidated however, no auto handshake retry happens.

The original scenario posted in this ticket is about IP discovery failing but I still don't have a solution to mitigate these. If above "retry" solution isn't enough, I think you could create a new GH issue with the feature request or [join our Discord](https://discord.gg/NxGAeCY) so it can be discussed.

**Comment by reptar25** [comment]
I have this same issue, but when moved to a EC2 instance with 2 CPUs instead of the t2.micro with 1, it works fine. On the t2.micro the bot only seems to disconnect when joining, like described above. Maybe a threading issue or something?

**Comment by EUB-LE** [comment]
Posting here first, because the symptons are identical. I can confirm the situation of @reptar25. For a simple bot the voice connection **does not work for EC2 t2.micro (1 CPU), but it works for t3.micro (2 CPUs)**. Here are the last few lines after the join should happen. 
On t2.micro: 
```
[parallel-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription [...] to VoiceStateUpdateEvent disposed due to cancel
[parallel-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription [...] to VoiceServerUpdateEvent disposed due to cancel
[parallel-2] DEBUG d.voice.LocalVoiceConnectionRegistry - No connection in registry to guild [...]

```
On t3.micro:
```
[d4j-events-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription [...] to VoiceStateUpdateEvent disposed due to cancel
[d4j-events-2] DEBUG d.c.event.ReplayingEventDispatcher - Subscription [...] to VoiceServerUpdateEvent disposed due to cancel
[reactor-http-epoll-3] DEBUG d.voice.DefaultVoiceGatewayClient - [...] [connected] PooledConnection{channel=[...]}
```

The identifiers at the start of the log are different. Does this point to a threading problem?

**Comment by Kosert** [comment]
Having exact same issue using OVH Starter VPS with 1 vCore. Bot joins voice, but disconnects after 10 seconds.
Ubuntu 20.10, firewall disabled.

**Comment by kowai-hm** [comment]
Hi ! I had that issue on a VPS with 1 vCPU. I solved the issue by upgrading the VPS to 2 vCPUs. It's definitely a multithreading issue.

**Comment by asoares1-chwy** [comment]
Confirmed there appears to be an issue running with 1 vCPU Amazon servers. Converting from `t2.micro` -> `t3.nano` EC2 instance instantly resolved the issue. Under some circumstances, you may be eligible to use `t3.nano` under the AWS free tier.
