### ISSUE TITLE
Application not starting due to reactor-core

### ISSUE THREAD

**Issue by jbonnici94** [Discord4J/Discord4J#797]
**To Reproduce:** I have created a bot with Spring in previous versions and just tried to bump up the library version

**Expected Behavior:** Startup successfully

**Actual Behavior:** Giving following exception:
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    discord4j.common.ReactorResources.<clinit>(ReactorResources.java:44)

The following method did not exist:

    'reactor.core.scheduler.Scheduler reactor.core.scheduler.Schedulers.boundedElastic()'

The method's class, reactor.core.scheduler.Schedulers, is available from the following locations:

    jar:file:/......./.m2/repository/io/projectreactor/reactor-core/3.2.11.RELEASE/reactor-core-3.2.11.RELEASE.jar!/reactor/core/scheduler/Schedulers.class

It was loaded from the following location:

    file:/..../.m2/repository/io/projectreactor/reactor-core/3.2.11.RELEASE/reactor-core-3.2.11.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of reactor.core.scheduler.Schedulers

**Version:** 3.1.1

**Other:** Spring version is 2.1.7.RELEASE

**Comment by quanticc** [comment]
Are you able to upgrade to spring-boot 2.2? There is an incompatibility due to the method not existing in *your* classpath. We don't shade reactor within D4J so the following applies:

- Discord4J 3.1.x depends on reactor 3.3 and it works with spring-boot 2.2 and newer
- Discord4J 3.0.x depends on reactor 3.2 and it works with spring-boot 2.1

Let me know if this helps

**Comment by jbonnici94** [comment]
ok thanks this fixed it for me!
