### ISSUE TITLE
Message#getAuthor will be empty for slash commands messages

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#911]
**To Reproduce:**

1. Send a follow-up message with a bot
2. Display the author of this message

**Expected Behavior:** The bot is returned as the author.

**Actual Behavior:** `Optional.empty` is returned.

**Version:** Affects both 3.1.x and 3.2.x

**Other:** This is due to the fact that `getAuthor` checks if the message is a webhook and returns empty if true.

**Workaround:** Use `Message#getUserData`

**Comment by darichey** [comment]
I'm interested in dropping the `Optional` from this method in 3.2. If I recall correctly, the logic was that the webhook user isn't "real," so we don't return it in that case. In retrospect, I don't think this makes sense, because Discord provides all of the necessary data to make a `User`. In fact, we're hiding potentially useful data like the webhook name. Thoughts?

**Comment by quanticc** [comment]
I agree, but can we do this without breaking existing assumptions? Maybe a transitional method for 3.2 + deprecating Optional variant, then removing in 3.3 - it's too late in 3.2 development to break such API
