### ISSUE TITLE
Improve message components editing

### ISSUE THREAD

**Issue by cottoncammy** [Discord4J/Discord4J#974]
**Feature Description:** The `Message::getComponents` method currently returns `List<MessageComponent>` but the `MessageEditSpec::setComponents` method requires a `List<LayoutComponent>`. One of these return types should therefore be changed to allow interoperability between the two. 

Additionally, some kind of `MessageEditSpec::addComponent` method should possibly be introduced to make it possible to add a new component to a message's existing components at the last action row, where possible. For example, if the component to be added is a button and the message has an existing, non-full action row, the button should be inserted at the end of this action row. Likewise, if the component cannot fit in the last action row, then a new action row should be inserted before adding the component. And if the message has no action rows and the component requires one, it should also be inserted before adding the component. One could also somehow choose to insert the passed component on a new action row even if the message's last action row isn't full.

I'd also like to suggest a `MessageEditSpec::removeComponent` method which would remove a single message component from a message. The method could accept a custom id which would remove the component with the given id, and possibly an overload which would accept an index and remove the corresponding component (e.g. an index of 0 would remove the first component, 1 the second component, etc.). 

**Justification:** It currently isn't possible to edit a message's components by passing in its current components due to the conflicting return types. Additionally, the proposed `addComponent` and `removeComponent` methods would improve the user experience for managing message components on a pre-existing message.

**Comment by darichey** [comment]
The first suggestion is definitely reasonable, and I've implemented it in c99de0b1b03d8583949da484ee9186e0fba20c94.

I don't think `addComponent` is a good idea, because where the component goes is arbitrary (i.e., adding it to the last action row if it's not full, otherwise adding a new action row). This could be bad if (when) in the future, Discord adds more layout components. `removeComponent` specifically by custom ID doesn't seem to suffer from this same problem, so maybe it could be added, but its presence might be confusing.

Instead, I think it would be better to have these "modifying" methods on `ActionRow` itself (e.g., `ActionRow#withAddedComponent(ActionComponent)` and `ActionRow#withRemovedComponent(String customId)`). This keeps the "where does the component go" decision isolated to this specific layout component.

We can keep this issue open to track that feature.

**Comment by cameronprater** [comment]
This does seem like a much better idea! 👏
